version: '3'
services:
  wordpress:
    build: ./DK-wp
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wordpress:/wordpress
      - ./local-scripts:/localscripts
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      DEV_THEME_USERNAME: titaniumbones
      DEV_THEME_REPONAME: understrap
      DEV_THEME_BRANCH: dockerize
      # PLUGINS: >-
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
  gulp:
    build: ./DK-gulp
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./wordpress:/wordpress
      - ./local-scripts:/local-scripts
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      DEV_THEME_USERNAME: titaniumbones
      DEV_THEME_REPONAME: understrap
      DEV_THEME_BRANCH: dockerize
volumes:
  data:
