version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./plugins:/app/wp-content/plugins
      - ./themes:/app/wp-content/themes
      - ./uploads:/app/wp-content/uploads
      # - ./dev-theme:/app/wp-content/themes/dev-theme
      # - ./dev-plugin:/app/wp-content/plugins/dev-plugin
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      DEV_THEME_USERNAME: holger1411
      DEV_THEME_REPONAME: understrap
      # PLUGINS: >-
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
  gulp:
    build: ./
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./themes:/themes
      - ./local-scripts:/local-scripts

volumes:
  data:
